# Generated by Django 5.0.6 on 2024-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicianAp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='Instrument_Type',
            field=models.CharField(choices=[('Grid', 'Grid'), ('Flute', 'Flute'), ('Piano', 'Piano'), ('Trumpet', 'Trumpet'), ('Banjo', 'Banjo')], default='Grid', max_length=10),
        ),
    ]
