# Generated by Django 5.0.6 on 2024-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicianAp', '0002_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('instrument_type', models.CharField(choices=[('Grid', 'Grid'), ('Flute', 'Flute'), ('Piano', 'Piano'), ('Trumpet', 'Trumpet'), ('Banjo', 'Banjo')], default='Grid', max_length=10)),
            ],
        ),
    ]
