# Generated by Django 5.0.6 on 2024-06-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumAp', '0002_alter_album_musiciam'),
        ('musicianAp', '0003_musicianmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='musician',
        ),
    ]
