# Generated by Django 5.0.6 on 2024-06-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicianAp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulbum_name', models.CharField(max_length=35)),
                ('relese_date', models.DateField(verbose_name='Date')),
                ('Ratting', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('musiciam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicianAp.musician')),
            ],
        ),
    ]
