# Generated by Django 5.0.6 on 2024-06-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumAp', '0001_initial'),
        ('musicianAp', '0003_musicianmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musiciam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicianAp.musicianmodel'),
        ),
    ]
